"""Initial State

Revision ID: 605a6ef75c1f
Revises: Initial State of Alembic for stage testing
Create Date: 2023-10-17 12:17:06.358193

"""

# revision identifiers, used by Alembic.
revision = "605a6ef75c1f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
