"""add support for verify prereq apis

Revision ID: f141bd683556
Revises: 5722be28483d
Create Date: 2024-07-30 16:43:25.682493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f141bd683556'
down_revision = '5722be28483d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_prereq', sa.Column('prereq_denied_reason', sa.TEXT(), nullable=True))
    op.add_column('enrollment_prereq', sa.Column('prereq_denied_response', sa.TEXT(), nullable=True))
    op.add_column('enrollment_prereq', sa.Column('assigned_team', sa.TEXT(), nullable=True))
    op.add_column('enrollment_prereq', sa.Column('cert_submission_attempts', sa.INTEGER(), nullable=True))
    op.add_column('enrollment_prereq', sa.Column('exp_proof_submission_attempts', sa.INTEGER(), nullable=True))
    op.alter_column(
        'enrollment_prereq',
        'status',
        existing_type=postgresql.ENUM('waiting_support', 'pending', 'approved', 'denied', name='prereqstatus'),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'enrollment_prereq',
        'status',
        existing_type=postgresql.ENUM('waiting_support', 'pending', 'approved', 'denied', name='prereqstatus'),
        nullable=False
    )
    op.drop_column('enrollment_prereq', 'exp_proof_submission_attempts')
    op.drop_column('enrollment_prereq', 'cert_submission_attempts')
    op.drop_column('enrollment_prereq', 'assigned_team')
    op.drop_column('enrollment_prereq', 'prereq_denied_response')
    op.drop_column('enrollment_prereq', 'prereq_denied_reason')
    # ### end Alembic commands ###
